- hosts: all
  become: true
  vars_prompt:
  - name: user_name
    prompt: Enter the user name for password reset
    private: no
  - name: pass
    prompt: Enter the password
  tasks:
  - name: Change {{ user_name }}  password
    user: name={{ user_name }} password={{ pass|password_hash('sha512') }} update_password=always
